name: Build the package

on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  RICE_FLAKE: github:emacs-twist/rice-config
  MELPA_FLAKE: github:akirak/melpa/akirak

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V27

      - name: Get the matrix
        id: matrix
        run: |
          echo "matrix=$(\
            nix eval "${RICE_FLAKE}#github.matrix" \
            --override-input rice-src "path:$PWD" --override-input melpa "${MELPA_FLAKE}" \
            --json)" >> "$GITHUB_OUTPUT"

  check-compile:
    needs: generate-matrix

    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Byte compile
        run: |
          nix build \
            "${RICE_FLAKE}#checks.${{ matrix.arch }}.${{ matrix.target }}-compile-${{ matrix.emacs }}" \
            --override-input rice-src "path:$PWD" --override-input melpa "${MELPA_FLAKE}" \
            --print-build-logs
