name: Check Emacs Lisp

on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'

  workflow_dispatch:

jobs:
  byte-compile:
    uses: emacs-twist/elisp-workflows/.github/workflows/compile-and-test.yml@master
    with:
      melpa: github:akirak/melpa/akirak
      systems: github:nix-systems/x86_64-linux
      lock-dir: ''
